library(shiny)

shinyUI(pageWithSidebar(
                        headerPanel("Categorization + RAPPOR Simulation"),
                        sidebarPanel(
                                     tabsetPanel(
                                       tabPanel("Population",
                                                br(),
                                                fileInput('datafile', 'Choose CSV file',
                                                          accept=c('text/csv', 'text/comma-separated-values,text/plain')),
                                                br(),
                                                sliderInput("nsamp", "Number of Samples:",
                                                            min = 0, max = 100, value = 30, step = 10),
                                                br(),
                                                sliderInput("nstrs", "Number of Categroies:",
                                                            min = 10, max = 100, value = 20, step = 10),
                                                br(),
                                                #sliderInput("nonzero", "Proportion of non-zero strings:",
                                                #            min = .1, max = 1, value = 0.5, step = .1),
                                                #br(),
                                                #selectInput("decay", "Decay of non-zero strings",
                                                #            c("Linear", "Exponential", "Constant","BostonSalary_Uniform","BostonSalary_Density"),
                                                #            selected = "Exponential"),
                                                #br(),
                                                #conditionalPanel(condition = "input.decay == 'Exponential'",
                                                #                 sliderInput("expo", "Rate of exponential decay",
                                                #                             min = 1, max = 200, value = 10, step = 1)),
                                                #sliderInput("background", "Frequency of background strings:",
                                                #            min = 0, max = .2, value = .05, step = .01),
                                                br(),
                                                br(),
                                                br()
                                       ),                                       
                                                 tabPanel("RAPPOR",
                                                          selectInput("size", "Bloom filter size:",
                                                                      c(4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096),
                                                                      selected = 128),
                                                          selectInput("hashes", "Number of hash functions:",
                                                                      c(1, 2, 4, 8, 16, 32),
                                                                      selected = 32),
                                                          selectInput("instances", "Number of cohorts:",
                                                                      c(1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024),
                                                                      selected = 8),
                                                          br(),
                                                          br(),
                                                          #sliderInput("N", "Number of samples to generate:",
                                                          #            min = 10000, max = 10000000,
                                                          #            value = 10000, step = 10000),
                                                          br(),
                                                          helpText(actionButton("sample", "Rerun Simulations"), align = "center"),
                                                          br(),
                                                          br(),
                                                          helpText("Version 0.1", align = "center"),
                                                          helpText(a("RAPPOR Repository", href="http://github.com/google/rappor"), align = "center")),
                                                 tabPanel("Privacy",
                                                          sliderInput("p", "Probability of reporting noise (p):",
                                                                      min = .01, max = .99, value = .5, step = .01),
                                                          sliderInput("q", "Probability of reporting signal (q):",
                                                                      min = .01, max = .99, value = .75, step = .01),
                                                          sliderInput("f", "Probability of lies (f):",
                                                                      min = 0, max = .99, value = .5, step = .01),
                                                          br(),
                                                          htmlOutput("epsilon"),
                                                          br(),
                                                          helpText("* In addition to p, q and f, the number of hash functions (set in the RAPPOR tab) also effects privacy guarantees."),
                                                          br(),
                                                          br(),
                                                          br()
                                                          ),
                                                 tabPanel("Decoding",
                                                          sliderInput("alpha", "Alpha - probability of false positive:",
                                                                      min = .01, max = .3, value = .05, step = .01),
                                                          br(),
                                                          selectInput("correction", "Multiple testing correction",
                                                                      c("None", "Bonferroni", "FDR"),
                                                                      selected = "None"),
                                                          br(),
                                                          sliderInput("missing", "Proportion of non-zero strings missing from decoding:",
                                                                      min = 0, max = 1, value = 0, step = .1),
                                                          br()
                                                          )
                                     )),
                        mainPanel(
                                  tabsetPanel(
                                              tabPanel("Categorization", plotOutput("probs", height = "600px")),
                                              tabPanel("Life of a  Report",
                                                       actionButton("new_user", "New Participant"),
                                                       actionButton("new_value", "New Value"),
                                                       actionButton("new_report", "New Report"),
                                                       plotOutput("example", height = "600px")),
                                              tabPanel("Results", helpText(h3("Summary")), htmlOutput("pr"), br(), br(), dataTableOutput("tab")),
                                              #tabPanel("True Bits", plotOutput("truth", height = "800px")),
                                              #tabPanel("Estimated Bits", plotOutput("ests", height = "800px")),
                                              tabPanel("Estimates vs Truth (Biplot)", plotOutput("ests_truth", height = "600px")),
                                              # tabPanel("Lasso", plotOutput("lasso", height = "600px")),
                                              #tabPanel("Residuals", plotOutput("resid", height = "600px"))
                                              tabPanel("Estimates vs Truth (Histogram)", plotOutput("ests_truth_hist", height = "600px"))
                                              )
                                  )
                        ))
